services:
  - type: web
    name: policy-management-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: policy-management
          property: connectionString
      - key: PORT
        value: 5000
